### ISSUE TITLE
Update litellm version to support OpenAI o1 models

### ISSUE THREAD

**Issue by shatu** [allenai/recoma#1]
LiteLLM started supporting OpenAI o1 models from version 1.44.276 onwards: https://github.com/BerriAI/litellm/releases/tag/v1.44.27

**Comment by tusharkhot** [comment]
There are many new parameters needed for o1. One option would be for downstream libraries to write a new generator class (e.g. similar to https://github.com/allenai/recoma/blob/main/recoma/models/impl/openai_generators.py) and register it. Happy to also accept PRs to this library for something like an `OpenAIO1Generator`.

**Comment by tusharkhot** [comment]
For now, I have added special code in the `openai_chat` model to change parameters when it sees an o1 model. 
https://github.com/allenai/recoma/commit/51ac88ed55d846641a5c789f70e422609e661814
